import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * The PanelSwitcherController class is the controller in this
 * application.  Its sole function is
 * to interpret events from the GUI and update instances of 
 * PanelSwitcherModel and PanelSwitcherView as appropriate.
 * 
 * @author Dusan Makevic
 */
public class PanelSwitcherController implements ActionListener {

	private PanelSwitcherModel model;
	private PanelSwitcherView view;
	
	/**
	 * This saves the model and and view.
	 * 
	 * @param model a PanelSwitcherModel for the choice of the panel
	 * @param view a PanelSwitcherView for what should be displayed in the GUI
	 */
	public PanelSwitcherController(PanelSwitcherView view, PanelSwitcherModel model) {
		
		this.model = model;
		this.view = view;
		
	}
	
	/**
	 * Determines what to do with the event generated by the GUI.
	 * The model and the view are updated as appropriate.
	 *  
	 * @param e an event from the GUI
	 */
	public void actionPerformed(ActionEvent e) {
		String command = e.getActionCommand();
		if (command == "Switch Panels"){
			model.switchPanel();
			view.displayPanel(model.whichPanel());
		}
	}
}
